spring:
  cloud:
    gateway:
      # 动态路由
      dynamic-route:
        type: redis
        enabled: true
      server:
        webflux:
          enabled: true
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true
          routes:
            - id: wemirr-platform-iam
              uri: lb://wemirr-platform-iam
              predicates:
                - Path=/iam/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 100   # 允许用户每秒处理多少个请求
                    redis-rate-limiter.burstCapacity: 100   # 令牌桶的容量，允许在一秒钟内完成的最大请求数
                    # 使用 IP 限流策略（使用 SpEL 按名称引用 bean）
                    key-resolver: "#{@ipKeyResolver}"
                - StripPrefix=1
                - PreserveHostHeader
                - name: Retry
                  args:
                    retries: 1
                    statuses: BAD_GATEWAY
                    backoff:
                      firstBackoff: 200ms
                      maxBackoff: 500ms
                      factor: 1
                      basedOnPreviousValue: false
                      exceptions: TimeoutException
            - id: wemirr-platform-iam-ws
              uri: lb:ws://wemirr-platform-iam
              predicates:
                - Path=/iam/**
              filters:
                - StripPrefix=1
            - id: wemirr-platform-suite
              uri: lb://wemirr-platform-suite
              predicates:
                - Path=/suite/**
              filters:
                - StripPrefix=1
                - PreserveHostHeader
            - id: wemirr-platform-monitor
              uri: lb://wemirr-platform-monitor
              predicates:
                - Path=/monitor/**
              filters:
                - StripPrefix=1
                - PreserveHostHeader
            - id: wemirr-platform-demo
              uri: lb://wemirr-platform-demo
              predicates:
                - Path=/demo/**
              filters:
                - StripPrefix=1
                - PreserveHostHeader
            - id: wemirr-platform-wms
              uri: lb://wemirr-platform-wms
              predicates:
                - Path=/wms/**
              filters:
                - StripPrefix=1
                - PreserveHostHeader
            - id: wemirr-platform-tms
              uri: lb://wemirr-platform-tms
              predicates:
                - Path=/tms/**
              filters:
                - StripPrefix=1
                - PreserveHostHeader
            - id: wemirr-platform-bpm
              uri: lb://wemirr-platform-bpm
              predicates:
                - Path=/bpm/**
              filters:
                - StripPrefix=1
                - PreserveHostHeader
            - id: wemirr-platform-workflow
              uri: lb://wemirr-platform-workflow
              predicates:
                - Path=/workflow/**
              filters:
                - StripPrefix=1
                - PreserveHostHeader
            - id: wemirr-platform-ai
              uri: lb://wemirr-platform-ai
              predicates:
                - Path=/ai/**
              filters:
                - StripPrefix=1
                - PreserveHostHeader
            # Gateway Admin 服务路由（网关管理接口）
            - id: wemirr-platform-gateway-admin
              uri: lb://wemirr-platform-gateway-admin
              predicates:
                - Path=/gateway/admin/**
              filters:
                - StripPrefix=2
                - PreserveHostHeader
          loadbalancer:
            use404: true
          httpclient:
            compression: true
            response-timeout: 300s
            pool:
              type: elastic
              max-idle-time: 30s
              max-connections: 1000
              acquire-timeout: 180000